name: Manual Image Sender
on:
    workflow_dispatch: # Allows manual trigger

jobs:
    send-images:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'
            - uses: browser-actions/setup-chrome@v1
              with:
                  install-chromedriver: true
                  install-dependencies: true
            - name: Update PATH for chrome
              run: |
                  sudo ln -sf /opt/hostedtoolcache/setup-chrome/chromium/stable/x64/chrome /usr/bin/google-chrome

            - name: Install Python dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install selenium pyyaml google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

            - name: Create config file
              env:
                  EMAIL_LIST: ${{ secrets.EMAIL_LIST }}
                  SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
                  SMTP_PORT: ${{ secrets.SMTP_PORT }}
                  SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                  SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
                  SA_CREDENTIALS: ${{ secrets.SA_CREDENTIALS }}
                  LEAGUE_ID_LIST: ${{ secrets.LEAGUE_ID_LIST }}
                  TEAM_ID_LIST: ${{ secrets.TEAM_ID_LIST }}
                  USER_ID_LIST: ${{ secrets.USER_ID_LIST }}
                  SKIP_LIST: ${{ secrets.SKIP_LIST }}
                  DISALLOWED_BUYS: ${{ secrets.DISALLOWED_BUYS }}
              run: |
                  echo "email_list: ${EMAIL_LIST}" > config.yaml
                  echo "smtp_server: ${SMTP_SERVER}" >> config.yaml
                  echo "smtp_port: ${SMTP_PORT}" >> config.yaml
                  echo "sender_email: ${SENDER_EMAIL}" >> config.yaml
                  echo "sender_password: ${SENDER_PASSWORD}" >> config.yaml
                  echo "league_id_list: ${LEAGUE_ID_LIST}" >> config.yaml
                  echo "team_id_list: ${TEAM_ID_LIST}" >> config.yaml
                  echo "user_id_list: ${USER_ID_LIST}" >> config.yaml
                  echo "skip_list: ${SKIP_LIST}" >> config.yaml
                  echo "disallowed_buys: ${DISALLOWED_BUYS}" >> config.yaml
                  echo "${SA_CREDENTIALS}" > service-account-credentials.json

            - name: Run image sender
              run: python scripts/infinite_bp/monthly_image_sender.py -s=1

            - uses: actions/upload-artifact@v4
              with:
                  path: |
                      email_to_buys.json
                      league_id_to_buys.json
